# Generated by Django 2.1.7 on 2019-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_empresa_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuesto',
            name='pri_dia',
            field=models.IntegerField(default=0),
        ),
    ]
