# Generated by Django 2.1.7 on 2019-05-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_impuesto_pri_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impuesto',
            old_name='tipo_iva',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='impuesto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
