# Generated by Django 2.1.7 on 2019-05-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20190526_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_imp',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='emp_imp',
            name='impuesto',
        ),
        migrations.RemoveField(
            model_name='emp_user',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='emp_user',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='impuesto',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='empresa',
            name='assignado_a',
            field=models.ManyToManyField(related_name='empresa_impuesto', to='common.Impuesto'),
        ),
        migrations.DeleteModel(
            name='Emp_Imp',
        ),
        migrations.DeleteModel(
            name='Emp_User',
        ),
    ]
