# Generated by Django 2.1.7 on 2019-05-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20190526_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='assignado_a',
            new_name='asignado_a',
        ),
    ]
