# Generated by Django 2.1.7 on 2019-05-30 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20190526_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['-is_active', 'nombre']},
        ),
    ]
