# Generated by Django 2.2.3 on 2019-08-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20190530_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='DGR',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
