# Generated by Django 2.2.3 on 2019-08-13 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_empresa_dgr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vencimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('terminacion', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuesto_vencimiento', to='common.Impuesto')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
