# Generated by Django 2.2.3 on 2019-08-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_vencimientos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vencimientos',
            new_name='Vencimiento',
        ),
    ]
