# Generated by Django 2.2.3 on 2019-08-13 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20190813_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vencimiento',
            options={'ordering': ['vencimiento']},
        ),
        migrations.RenameField(
            model_name='vencimiento',
            old_name='fecha',
            new_name='periodo',
        ),
        migrations.AddField(
            model_name='vencimiento',
            name='vencimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
