# Generated by Django 2.1.7 on 2019-05-31 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='asignado_a',
            field=models.ManyToManyField(blank=True, null=True, related_name='novedad_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
