# Generated by Django 2.1.7 on 2019-06-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feriados',
            new_name='Feriado',
        ),
    ]
