# Generated by Django 2.1.7 on 2019-06-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0002_auto_20190608_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feriado',
            options={'ordering': ['-fecha']},
        ),
    ]
