# Generated by Django 2.1.7 on 2019-06-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0003_auto_20190609_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
